// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserDefaultAddresses = `-- name: ClearUserDefaultAddresses :exec
UPDATE addresses
SET is_default = FALSE
WHERE user_id = $1
`

func (q *Queries) ClearUserDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearUserDefaultAddresses, userID)
	return err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
    user_id,
    label,
    recipient_name,
    phone,
    street_address,
    city,
    state,
    postal_code,
    country,
    is_default
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, label, recipient_name, phone, street_address, city, state, postal_code, country, is_default, created_at
`

type CreateAddressParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Label         pgtype.Text `json:"label"`
	RecipientName string      `json:"recipient_name"`
	Phone         pgtype.Text `json:"phone"`
	StreetAddress string      `json:"street_address"`
	City          string      `json:"city"`
	State         pgtype.Text `json:"state"`
	PostalCode    string      `json:"postal_code"`
	Country       string      `json:"country"`
	IsDefault     pgtype.Bool `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.RecipientName,
		arg.Phone,
		arg.StreetAddress,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses
WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, label, recipient_name, phone, street_address, city, state, postal_code, country, is_default, created_at FROM addresses
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, label, recipient_name, phone, street_address, city, state, postal_code, country, is_default, created_at FROM addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.RecipientName,
			&i.Phone,
			&i.StreetAddress,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET
    label = COALESCE($2, label),
    recipient_name = COALESCE($3, recipient_name),
    phone = COALESCE($4, phone),
    street_address = COALESCE($5, street_address),
    city = COALESCE($6, city),
    state = COALESCE($7, state),
    postal_code = COALESCE($8, postal_code),
    country = COALESCE($9, country),
    is_default = COALESCE($10, is_default)
WHERE id = $1
RETURNING id, user_id, label, recipient_name, phone, street_address, city, state, postal_code, country, is_default, created_at
`

type UpdateAddressParams struct {
	ID            uuid.UUID   `json:"id"`
	Label         pgtype.Text `json:"label"`
	RecipientName pgtype.Text `json:"recipient_name"`
	Phone         pgtype.Text `json:"phone"`
	StreetAddress pgtype.Text `json:"street_address"`
	City          pgtype.Text `json:"city"`
	State         pgtype.Text `json:"state"`
	PostalCode    pgtype.Text `json:"postal_code"`
	Country       pgtype.Text `json:"country"`
	IsDefault     pgtype.Bool `json:"is_default"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Label,
		arg.RecipientName,
		arg.Phone,
		arg.StreetAddress,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}
