// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmStockDeduction = `-- name: ConfirmStockDeduction :one
UPDATE inventory
SET quantity = quantity - $2,
    reserved_quantity = GREATEST(reserved_quantity - $2, 0),
    updated_at = NOW()
WHERE variant_id = $1 AND quantity >= $2
RETURNING id, variant_id, quantity, reserved_quantity, low_stock_threshold, updated_at
`

type ConfirmStockDeductionParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) ConfirmStockDeduction(ctx context.Context, arg ConfirmStockDeductionParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, confirmStockDeduction, arg.VariantID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.LowStockThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const countInventory = `-- name: CountInventory :one
SELECT COUNT(*) FROM inventory
`

func (q *Queries) CountInventory(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInventory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory (variant_id, quantity, reserved_quantity, low_stock_threshold)
VALUES ($1, $2, $3, $4)
RETURNING id, variant_id, quantity, reserved_quantity, low_stock_threshold, updated_at
`

type CreateInventoryItemParams struct {
	VariantID         uuid.UUID   `json:"variant_id"`
	Quantity          int32       `json:"quantity"`
	ReservedQuantity  int32       `json:"reserved_quantity"`
	LowStockThreshold pgtype.Int4 `json:"low_stock_threshold"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.VariantID,
		arg.Quantity,
		arg.ReservedQuantity,
		arg.LowStockThreshold,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.LowStockThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (variant_id, movement_type, quantity, reason, reference_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, variant_id, movement_type, quantity, reason, reference_id, created_at
`

type CreateStockMovementParams struct {
	VariantID    uuid.UUID   `json:"variant_id"`
	MovementType string      `json:"movement_type"`
	Quantity     int32       `json:"quantity"`
	Reason       pgtype.Text `json:"reason"`
	ReferenceID  pgtype.UUID `json:"reference_id"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.VariantID,
		arg.MovementType,
		arg.Quantity,
		arg.Reason,
		arg.ReferenceID,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.MovementType,
		&i.Quantity,
		&i.Reason,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory WHERE variant_id = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, variantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, variantID)
	return err
}

const getInventoryByVariant = `-- name: GetInventoryByVariant :one
SELECT id, variant_id, quantity, reserved_quantity, low_stock_threshold, updated_at FROM inventory WHERE variant_id = $1
`

func (q *Queries) GetInventoryByVariant(ctx context.Context, variantID uuid.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByVariant, variantID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.LowStockThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventory = `-- name: ListInventory :many
SELECT i.id, i.variant_id, i.quantity, i.reserved_quantity, i.low_stock_threshold, i.updated_at, v.sku, v.variant_name, p.name as product_name
FROM inventory i
JOIN product_variants v ON i.variant_id = v.id
JOIN products p ON v.product_id = p.id
ORDER BY i.updated_at DESC
LIMIT $1 OFFSET $2
`

type ListInventoryParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListInventoryRow struct {
	ID                uuid.UUID          `json:"id"`
	VariantID         uuid.UUID          `json:"variant_id"`
	Quantity          int32              `json:"quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	LowStockThreshold pgtype.Int4        `json:"low_stock_threshold"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Sku               string             `json:"sku"`
	VariantName       pgtype.Text        `json:"variant_name"`
	ProductName       string             `json:"product_name"`
}

func (q *Queries) ListInventory(ctx context.Context, arg ListInventoryParams) ([]ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryRow{}
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Quantity,
			&i.ReservedQuantity,
			&i.LowStockThreshold,
			&i.UpdatedAt,
			&i.Sku,
			&i.VariantName,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockItems = `-- name: ListLowStockItems :many
SELECT i.id, i.variant_id, i.quantity, i.reserved_quantity, i.low_stock_threshold, i.updated_at, v.sku, v.variant_name, p.name as product_name
FROM inventory i
JOIN product_variants v ON i.variant_id = v.id
JOIN products p ON v.product_id = p.id
WHERE i.quantity <= i.low_stock_threshold
ORDER BY i.quantity ASC
`

type ListLowStockItemsRow struct {
	ID                uuid.UUID          `json:"id"`
	VariantID         uuid.UUID          `json:"variant_id"`
	Quantity          int32              `json:"quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	LowStockThreshold pgtype.Int4        `json:"low_stock_threshold"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Sku               string             `json:"sku"`
	VariantName       pgtype.Text        `json:"variant_name"`
	ProductName       string             `json:"product_name"`
}

func (q *Queries) ListLowStockItems(ctx context.Context) ([]ListLowStockItemsRow, error) {
	rows, err := q.db.Query(ctx, listLowStockItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLowStockItemsRow{}
	for rows.Next() {
		var i ListLowStockItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Quantity,
			&i.ReservedQuantity,
			&i.LowStockThreshold,
			&i.UpdatedAt,
			&i.Sku,
			&i.VariantName,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByVariant = `-- name: ListStockMovementsByVariant :many
SELECT id, variant_id, movement_type, quantity, reason, reference_id, created_at FROM stock_movements WHERE variant_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListStockMovementsByVariantParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListStockMovementsByVariant(ctx context.Context, arg ListStockMovementsByVariantParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByVariant, arg.VariantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockMovement{}
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.MovementType,
			&i.Quantity,
			&i.Reason,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseStock = `-- name: ReleaseStock :one
UPDATE inventory
SET reserved_quantity = GREATEST(reserved_quantity - $2, 0), updated_at = NOW()
WHERE variant_id = $1
RETURNING id, variant_id, quantity, reserved_quantity, low_stock_threshold, updated_at
`

type ReleaseStockParams struct {
	VariantID        uuid.UUID `json:"variant_id"`
	ReservedQuantity int32     `json:"reserved_quantity"`
}

func (q *Queries) ReleaseStock(ctx context.Context, arg ReleaseStockParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, releaseStock, arg.VariantID, arg.ReservedQuantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.LowStockThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveStock = `-- name: ReserveStock :one
UPDATE inventory
SET reserved_quantity = reserved_quantity + $2, updated_at = NOW()
WHERE variant_id = $1 AND (quantity - reserved_quantity) >= $2
RETURNING id, variant_id, quantity, reserved_quantity, low_stock_threshold, updated_at
`

type ReserveStockParams struct {
	VariantID        uuid.UUID `json:"variant_id"`
	ReservedQuantity int32     `json:"reserved_quantity"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, reserveStock, arg.VariantID, arg.ReservedQuantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.LowStockThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInventoryQuantity = `-- name: UpdateInventoryQuantity :one
UPDATE inventory
SET quantity = $2, updated_at = NOW()
WHERE variant_id = $1
RETURNING id, variant_id, quantity, reserved_quantity, low_stock_threshold, updated_at
`

type UpdateInventoryQuantityParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Quantity  int32     `json:"quantity"`
}

func (q *Queries) UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryQuantity, arg.VariantID, arg.Quantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.LowStockThreshold,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInventoryReserved = `-- name: UpdateInventoryReserved :one
UPDATE inventory
SET reserved_quantity = $2, updated_at = NOW()
WHERE variant_id = $1
RETURNING id, variant_id, quantity, reserved_quantity, low_stock_threshold, updated_at
`

type UpdateInventoryReservedParams struct {
	VariantID        uuid.UUID `json:"variant_id"`
	ReservedQuantity int32     `json:"reserved_quantity"`
}

func (q *Queries) UpdateInventoryReserved(ctx context.Context, arg UpdateInventoryReservedParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryReserved, arg.VariantID, arg.ReservedQuantity)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Quantity,
		&i.ReservedQuantity,
		&i.LowStockThreshold,
		&i.UpdatedAt,
	)
	return i, err
}
