// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Label         pgtype.Text        `json:"label"`
	RecipientName string             `json:"recipient_name"`
	Phone         pgtype.Text        `json:"phone"`
	StreetAddress string             `json:"street_address"`
	City          string             `json:"city"`
	State         pgtype.Text        `json:"state"`
	PostalCode    string             `json:"postal_code"`
	Country       string             `json:"country"`
	IsDefault     pgtype.Bool        `json:"is_default"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Resource  string             `json:"resource"`
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Bio          pgtype.Text        `json:"bio"`
}

type UserRole struct {
	UserID    uuid.UUID          `json:"user_id"`
	RoleID    uuid.UUID          `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
