// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Label         pgtype.Text        `json:"label"`
	RecipientName string             `json:"recipient_name"`
	Phone         pgtype.Text        `json:"phone"`
	StreetAddress string             `json:"street_address"`
	City          string             `json:"city"`
	State         pgtype.Text        `json:"state"`
	PostalCode    string             `json:"postal_code"`
	Country       string             `json:"country"`
	IsDefault     pgtype.Bool        `json:"is_default"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	SortOrder   pgtype.Int4        `json:"sort_order"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Inventory struct {
	ID                uuid.UUID          `json:"id"`
	VariantID         uuid.UUID          `json:"variant_id"`
	Quantity          int32              `json:"quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	LowStockThreshold pgtype.Int4        `json:"low_stock_threshold"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Resource  string             `json:"resource"`
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID               uuid.UUID          `json:"id"`
	CategoryID       pgtype.UUID        `json:"category_id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	Description      pgtype.Text        `json:"description"`
	ShortDescription pgtype.Text        `json:"short_description"`
	BasePrice        pgtype.Numeric     `json:"base_price"`
	CompareAtPrice   pgtype.Numeric     `json:"compare_at_price"`
	Status           pgtype.Text        `json:"status"`
	Gender           pgtype.Text        `json:"gender"`
	Sport            pgtype.Text        `json:"sport"`
	Brand            pgtype.Text        `json:"brand"`
	Tags             []string           `json:"tags"`
	WeightG          pgtype.Int4        `json:"weight_g"`
	MaterialInfo     pgtype.Text        `json:"material_info"`
	CareInstructions pgtype.Text        `json:"care_instructions"`
	AvgRating        pgtype.Numeric     `json:"avg_rating"`
	ReviewCount      pgtype.Int4        `json:"review_count"`
	SeoTitle         pgtype.Text        `json:"seo_title"`
	SeoDescription   pgtype.Text        `json:"seo_description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ProductImage struct {
	ID        uuid.UUID          `json:"id"`
	ProductID uuid.UUID          `json:"product_id"`
	VariantID pgtype.UUID        `json:"variant_id"`
	ImageUrl  string             `json:"image_url"`
	AltText   pgtype.Text        `json:"alt_text"`
	SortOrder pgtype.Int4        `json:"sort_order"`
	IsPrimary pgtype.Bool        `json:"is_primary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProductVariant struct {
	ID            uuid.UUID          `json:"id"`
	ProductID     uuid.UUID          `json:"product_id"`
	Sku           string             `json:"sku"`
	VariantName   pgtype.Text        `json:"variant_name"`
	ColorName     pgtype.Text        `json:"color_name"`
	ColorHex      pgtype.Text        `json:"color_hex"`
	SizeLabel     pgtype.Text        `json:"size_label"`
	SizeSystem    pgtype.Text        `json:"size_system"`
	PriceOverride pgtype.Numeric     `json:"price_override"`
	IsActive      pgtype.Bool        `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type StockMovement struct {
	ID           uuid.UUID          `json:"id"`
	VariantID    uuid.UUID          `json:"variant_id"`
	MovementType string             `json:"movement_type"`
	Quantity     int32              `json:"quantity"`
	Reason       pgtype.Text        `json:"reason"`
	ReferenceID  pgtype.UUID        `json:"reference_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Phone        pgtype.Text        `json:"phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Bio          pgtype.Text        `json:"bio"`
}

type UserRole struct {
	UserID    uuid.UUID          `json:"user_id"`
	RoleID    uuid.UUID          `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
