// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE deleted_at IS NULL
  AND (NULLIF($1, '00000000-0000-0000-0000-000000000000'::uuid) IS NULL OR category_id = $1)
  AND (NULLIF($2, '') IS NULL OR gender = $2)
  AND (NULLIF($3, '') IS NULL OR sport = $3)
  AND (NULLIF($4, '') IS NULL OR status = $4)
  AND (NULLIF($5, 0)::decimal IS NULL OR base_price >= $5)
  AND (NULLIF($6, 0)::decimal IS NULL OR base_price <= $6)
  AND ($7::text[] IS NULL OR tags && $7)
`

type CountProductsParams struct {
	CategoryID interface{} `json:"category_id"`
	Gender     interface{} `json:"gender"`
	Sport      interface{} `json:"sport"`
	Status     interface{} `json:"status"`
	PriceMin   interface{} `json:"price_min"`
	PriceMax   interface{} `json:"price_max"`
	Tags       []string    `json:"tags"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.CategoryID,
		arg.Gender,
		arg.Sport,
		arg.Status,
		arg.PriceMin,
		arg.PriceMax,
		arg.Tags,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, description, parent_id, sort_order, image_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, description, parent_id, sort_order, image_url, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	SortOrder   pgtype.Int4 `json:"sort_order"`
	ImageUrl    pgtype.Text `json:"image_url"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
		arg.ImageUrl,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.SortOrder,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    category_id, name, slug, description, short_description, base_price, compare_at_price,
    status, gender, sport, brand, tags, weight_g, material_info, care_instructions,
    seo_title, seo_description
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, category_id, name, slug, description, short_description, base_price, compare_at_price, status, gender, sport, brand, tags, weight_g, material_info, care_instructions, avg_rating, review_count, seo_title, seo_description, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	CategoryID       pgtype.UUID    `json:"category_id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      pgtype.Text    `json:"description"`
	ShortDescription pgtype.Text    `json:"short_description"`
	BasePrice        pgtype.Numeric `json:"base_price"`
	CompareAtPrice   pgtype.Numeric `json:"compare_at_price"`
	Status           pgtype.Text    `json:"status"`
	Gender           pgtype.Text    `json:"gender"`
	Sport            pgtype.Text    `json:"sport"`
	Brand            pgtype.Text    `json:"brand"`
	Tags             []string       `json:"tags"`
	WeightG          pgtype.Int4    `json:"weight_g"`
	MaterialInfo     pgtype.Text    `json:"material_info"`
	CareInstructions pgtype.Text    `json:"care_instructions"`
	SeoTitle         pgtype.Text    `json:"seo_title"`
	SeoDescription   pgtype.Text    `json:"seo_description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.BasePrice,
		arg.CompareAtPrice,
		arg.Status,
		arg.Gender,
		arg.Sport,
		arg.Brand,
		arg.Tags,
		arg.WeightG,
		arg.MaterialInfo,
		arg.CareInstructions,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.BasePrice,
		&i.CompareAtPrice,
		&i.Status,
		&i.Gender,
		&i.Sport,
		&i.Brand,
		&i.Tags,
		&i.WeightG,
		&i.MaterialInfo,
		&i.CareInstructions,
		&i.AvgRating,
		&i.ReviewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, variant_id, image_url, alt_text, sort_order, is_primary)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, variant_id, image_url, alt_text, sort_order, is_primary, created_at
`

type CreateProductImageParams struct {
	ProductID uuid.UUID   `json:"product_id"`
	VariantID pgtype.UUID `json:"variant_id"`
	ImageUrl  string      `json:"image_url"`
	AltText   pgtype.Text `json:"alt_text"`
	SortOrder pgtype.Int4 `json:"sort_order"`
	IsPrimary pgtype.Bool `json:"is_primary"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.VariantID,
		arg.ImageUrl,
		arg.AltText,
		arg.SortOrder,
		arg.IsPrimary,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.ImageUrl,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO product_variants (
    product_id, sku, variant_name, color_name, color_hex, size_label, size_system, price_override
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, sku, variant_name, color_name, color_hex, size_label, size_system, price_override, is_active, created_at
`

type CreateVariantParams struct {
	ProductID     uuid.UUID      `json:"product_id"`
	Sku           string         `json:"sku"`
	VariantName   pgtype.Text    `json:"variant_name"`
	ColorName     pgtype.Text    `json:"color_name"`
	ColorHex      pgtype.Text    `json:"color_hex"`
	SizeLabel     pgtype.Text    `json:"size_label"`
	SizeSystem    pgtype.Text    `json:"size_system"`
	PriceOverride pgtype.Numeric `json:"price_override"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ProductID,
		arg.Sku,
		arg.VariantName,
		arg.ColorName,
		arg.ColorHex,
		arg.SizeLabel,
		arg.SizeSystem,
		arg.PriceOverride,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.VariantName,
		&i.ColorName,
		&i.ColorHex,
		&i.SizeLabel,
		&i.SizeSystem,
		&i.PriceOverride,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImage, id)
	return err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM product_variants WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariant, id)
	return err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description, parent_id, sort_order, image_url, is_active, created_at, updated_at
FROM categories
WHERE slug = $1 AND is_active = true
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.SortOrder,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, name, slug, description, short_description, base_price, compare_at_price, status, gender, sport, brand, tags, weight_g, material_info, care_instructions, avg_rating, review_count, seo_title, seo_description, created_at, updated_at, deleted_at FROM products WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.BasePrice,
		&i.CompareAtPrice,
		&i.Status,
		&i.Gender,
		&i.Sport,
		&i.Brand,
		&i.Tags,
		&i.WeightG,
		&i.MaterialInfo,
		&i.CareInstructions,
		&i.AvgRating,
		&i.ReviewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, category_id, name, slug, description, short_description, base_price, compare_at_price, status, gender, sport, brand, tags, weight_g, material_info, care_instructions, avg_rating, review_count, seo_title, seo_description, created_at, updated_at, deleted_at FROM products WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.BasePrice,
		&i.CompareAtPrice,
		&i.Status,
		&i.Gender,
		&i.Sport,
		&i.Brand,
		&i.Tags,
		&i.WeightG,
		&i.MaterialInfo,
		&i.CareInstructions,
		&i.AvgRating,
		&i.ReviewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, variant_id, image_url, alt_text, sort_order, is_primary, created_at FROM product_images WHERE id = $1
`

func (q *Queries) GetProductImageByID(ctx context.Context, id uuid.UUID) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VariantID,
		&i.ImageUrl,
		&i.AltText,
		&i.SortOrder,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, product_id, sku, variant_name, color_name, color_hex, size_label, size_system, price_override, is_active, created_at FROM product_variants WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.VariantName,
		&i.ColorName,
		&i.ColorHex,
		&i.SizeLabel,
		&i.SizeSystem,
		&i.PriceOverride,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, parent_id, sort_order, image_url, is_active, created_at, updated_at
FROM categories
WHERE is_active = true
ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedProducts = `-- name: ListFeaturedProducts :many
SELECT id, category_id, name, slug, description, short_description, base_price, compare_at_price, status, gender, sport, brand, tags, weight_g, material_info, care_instructions, avg_rating, review_count, seo_title, seo_description, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL AND status = 'active'
  AND ('new' = ANY(tags) OR 'best-seller' = ANY(tags))
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListFeaturedProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, listFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.BasePrice,
			&i.CompareAtPrice,
			&i.Status,
			&i.Gender,
			&i.Sport,
			&i.Brand,
			&i.Tags,
			&i.WeightG,
			&i.MaterialInfo,
			&i.CareInstructions,
			&i.AvgRating,
			&i.ReviewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByProduct = `-- name: ListImagesByProduct :many
SELECT id, product_id, variant_id, image_url, alt_text, sort_order, is_primary, created_at FROM product_images WHERE product_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListImagesByProduct(ctx context.Context, productID uuid.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listImagesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantID,
			&i.ImageUrl,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByVariant = `-- name: ListImagesByVariant :many
SELECT id, product_id, variant_id, image_url, alt_text, sort_order, is_primary, created_at FROM product_images WHERE variant_id = $1 ORDER BY sort_order, created_at
`

func (q *Queries) ListImagesByVariant(ctx context.Context, variantID pgtype.UUID) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listImagesByVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VariantID,
			&i.ImageUrl,
			&i.AltText,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, category_id, name, slug, description, short_description, base_price, compare_at_price, status, gender, sport, brand, tags, weight_g, material_info, care_instructions, avg_rating, review_count, seo_title, seo_description, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL
  AND (NULLIF($1, '00000000-0000-0000-0000-000000000000'::uuid) IS NULL OR category_id = $1)
  AND (NULLIF($2, '') IS NULL OR gender = $2)
  AND (NULLIF($3, '') IS NULL OR sport = $3)
  AND (NULLIF($4, '') IS NULL OR status = $4)
  AND (NULLIF($5, 0)::decimal IS NULL OR base_price >= $5)
  AND (NULLIF($6, 0)::decimal IS NULL OR base_price <= $6)
  AND ($7::text[] IS NULL OR tags && $7)
ORDER BY
  CASE WHEN $8::varchar = 'price_asc' THEN base_price END ASC,
  CASE WHEN $8::varchar = 'price_desc' THEN base_price END DESC,
  CASE WHEN $8::varchar = 'newest' THEN created_at END DESC,
  CASE WHEN $8::varchar = 'rating' THEN avg_rating END DESC,
  CASE WHEN $8::varchar = '' OR $8::varchar IS NULL THEN created_at END DESC
LIMIT $10 OFFSET $9
`

type ListProductsParams struct {
	CategoryID interface{} `json:"category_id"`
	Gender     interface{} `json:"gender"`
	Sport      interface{} `json:"sport"`
	Status     interface{} `json:"status"`
	PriceMin   interface{} `json:"price_min"`
	PriceMax   interface{} `json:"price_max"`
	Tags       []string    `json:"tags"`
	SortBy     string      `json:"sort_by"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.CategoryID,
		arg.Gender,
		arg.Sport,
		arg.Status,
		arg.PriceMin,
		arg.PriceMax,
		arg.Tags,
		arg.SortBy,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.BasePrice,
			&i.CompareAtPrice,
			&i.Status,
			&i.Gender,
			&i.Sport,
			&i.Brand,
			&i.Tags,
			&i.WeightG,
			&i.MaterialInfo,
			&i.CareInstructions,
			&i.AvgRating,
			&i.ReviewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, sku, variant_name, color_name, color_hex, size_label, size_system, price_override, is_active, created_at FROM product_variants WHERE product_id = $1 AND is_active = true ORDER BY created_at
`

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID uuid.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.VariantName,
			&i.ColorName,
			&i.ColorHex,
			&i.SizeLabel,
			&i.SizeSystem,
			&i.PriceOverride,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryImage = `-- name: SetPrimaryImage :exec
UPDATE product_images SET is_primary = false WHERE product_id = $1
`

func (q *Queries) SetPrimaryImage(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPrimaryImage, productID)
	return err
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products SET deleted_at = NOW(), status = 'discontinued' WHERE id = $1
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, id)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2, slug = $3, description = $4, parent_id = $5, sort_order = $6, image_url = $7, is_active = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, description, parent_id, sort_order, image_url, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	SortOrder   pgtype.Int4 `json:"sort_order"`
	ImageUrl    pgtype.Text `json:"image_url"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
		arg.ImageUrl,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ParentID,
		&i.SortOrder,
		&i.ImageUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET category_id = $2, name = $3, slug = $4, description = $5, short_description = $6,
    base_price = $7, compare_at_price = $8, status = $9, gender = $10, sport = $11,
    brand = $12, tags = $13, weight_g = $14, material_info = $15, care_instructions = $16,
    seo_title = $17, seo_description = $18, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, category_id, name, slug, description, short_description, base_price, compare_at_price, status, gender, sport, brand, tags, weight_g, material_info, care_instructions, avg_rating, review_count, seo_title, seo_description, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	ID               uuid.UUID      `json:"id"`
	CategoryID       pgtype.UUID    `json:"category_id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      pgtype.Text    `json:"description"`
	ShortDescription pgtype.Text    `json:"short_description"`
	BasePrice        pgtype.Numeric `json:"base_price"`
	CompareAtPrice   pgtype.Numeric `json:"compare_at_price"`
	Status           pgtype.Text    `json:"status"`
	Gender           pgtype.Text    `json:"gender"`
	Sport            pgtype.Text    `json:"sport"`
	Brand            pgtype.Text    `json:"brand"`
	Tags             []string       `json:"tags"`
	WeightG          pgtype.Int4    `json:"weight_g"`
	MaterialInfo     pgtype.Text    `json:"material_info"`
	CareInstructions pgtype.Text    `json:"care_instructions"`
	SeoTitle         pgtype.Text    `json:"seo_title"`
	SeoDescription   pgtype.Text    `json:"seo_description"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.BasePrice,
		arg.CompareAtPrice,
		arg.Status,
		arg.Gender,
		arg.Sport,
		arg.Brand,
		arg.Tags,
		arg.WeightG,
		arg.MaterialInfo,
		arg.CareInstructions,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.BasePrice,
		&i.CompareAtPrice,
		&i.Status,
		&i.Gender,
		&i.Sport,
		&i.Brand,
		&i.Tags,
		&i.WeightG,
		&i.MaterialInfo,
		&i.CareInstructions,
		&i.AvgRating,
		&i.ReviewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE product_variants
SET sku = $2, variant_name = $3, color_name = $4, color_hex = $5,
    size_label = $6, size_system = $7, price_override = $8, is_active = $9
WHERE id = $1
RETURNING id, product_id, sku, variant_name, color_name, color_hex, size_label, size_system, price_override, is_active, created_at
`

type UpdateVariantParams struct {
	ID            uuid.UUID      `json:"id"`
	Sku           string         `json:"sku"`
	VariantName   pgtype.Text    `json:"variant_name"`
	ColorName     pgtype.Text    `json:"color_name"`
	ColorHex      pgtype.Text    `json:"color_hex"`
	SizeLabel     pgtype.Text    `json:"size_label"`
	SizeSystem    pgtype.Text    `json:"size_system"`
	PriceOverride pgtype.Numeric `json:"price_override"`
	IsActive      pgtype.Bool    `json:"is_active"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.ID,
		arg.Sku,
		arg.VariantName,
		arg.ColorName,
		arg.ColorHex,
		arg.SizeLabel,
		arg.SizeSystem,
		arg.PriceOverride,
		arg.IsActive,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.VariantName,
		&i.ColorName,
		&i.ColorHex,
		&i.SizeLabel,
		&i.SizeSystem,
		&i.PriceOverride,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
